[package]
name = "beetle-nonzero"
version = "0.2.1"
edition = "2021"
authors = ["beetle"]
description = "What if the built-in NonZero types were generic"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
num = "0.4.0"
