[package]
name = "beetle-nonzero"
version = "0.3.4"
edition = "2021"
authors = ["beetle"]
description = "The standard library's NonZeroU* types into a single struct"
license = "MIT"
repository = "https://github.com/Mearkatz/beetle-nonzero"


[dependencies]
num = "0.4.0"
